function t121_setHeight(recid){var rec=document.getElementById('rec'+recid);var videoBlock=document.getElementById('youtubeiframe'+recid);var videoParent=videoBlock?videoBlock.parentNode:null;var videoWidth=videoBlock?videoBlock.offsetWidth:0;var videoHeight=videoWidth*0.5625;if(videoBlock)videoBlock.style.height=videoHeight+'px';if(videoParent)videoParent.style.height=videoHeight+'px';var videoLazy=rec?rec.querySelector('.t-video-lazyload'):null;if(videoLazy){var iframeLazy=videoLazy.querySelector('iframe');var heightLazy=videoLazy.offsetWidth*0.5625;videoLazy.style.height=heightLazy+'px';if(iframeLazy)iframeLazy.style.height=heightLazy+'px';setTimeout(function(){videoBlock=document.getElementById('youtubeiframe'+recid);videoWidth=videoBlock?videoBlock.offsetWidth:0;if(videoBlock)videoBlock.style.height=(videoWidth*0.5625)+'px'},200)}}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=$('html, body');var target="";if(speed===undefined){speed=400}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=window.location.hash!==hash;var complete=function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
var dontChangeHistory=Boolean($('.t270').attr('data-history-disabled'));if(dontChangeHistory){complete=function(){}}
root.animate({scrollTop:target.offset().top-offset},speed,complete);return!0}
function t395_init(recid){var el=$('#rec'+recid);var curMode=$('.t-records').attr('data-tilda-mode');var tabs=el.find('.t395__tab');if(curMode!='edit'&&curMode!='preview'){t395_scrollToTabs(recid)}
if(tabs.length>0){tabs.on('click',function(event){if($(this).hasClass('t395__tab_active')&&event.isTrigger!==3){return}
el.find('.t395__tab').removeClass('t395__tab_active');$(this).addClass('t395__tab_active');t395_removeUrl();var tabNumber=el.find(".t395__tab_active").index()+1;if(curMode!='edit'&&curMode!='preview'&&tabNumber!==0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
t395_alltabs_updateContent(recid);t395_updateSelect(recid);var recids=$(this).attr('data-tab-rec-ids').split(',');recids.forEach(function(recid){var el=$('#rec'+recid);el.find('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t448, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t569, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t902, .t912, .t923, .t937, .t959, .t979, .t982, .t983, .t989, .t994').trigger('displayChanged')});$('.t826').trigger('displayChanged');t395_startUpdateLazyLoad($(this));if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});t395_alltabs_updateContent(recid);t395_updateContentBySelect(recid);var bgcolor=el.css("background-color");var bgcolor_target=el.find(".t395__select, .t395__firefoxfix");bgcolor_target.css("background",bgcolor)}}
function t395_alltabs_updateContent(recid){var mainRecid=recid;var el=$('#rec'+recid);var activeTab=el.find(".t395__tab_active");if(activeTab.length===1){var active=activeTab.attr('data-tab-rec-ids').split(',');var noactive=[];el.find(".t395__tab:not(.t395__tab_active)").each(function(i,tab){noactive=noactive.concat($(tab).attr('data-tab-rec-ids').split(','))});var unique=noactive.filter(function(value,index,self){return self.indexOf(value)===index});var off=unique.filter(function(value){return $.inArray(value,active)===-1});if(el.find(".t395__tab_active").is(":visible")||el.find(".t395__select").is(":visible")){active.forEach(function(recid){if(recid!==''){var el=$('#rec'+recid);var recordType=el.attr('data-record-type');el.removeClass('t395__off');el.css('opacity','');if(recordType==='395'&&mainRecid!==recid){t395_alltabs_updateContent(recid);t395_updateSelect(recid);el.find('.t395__tab:nth-child(1)').trigger('click')}
if(recordType==='397'&&t397_alltabs_updateContent!==undefined&&t397_updateSelect!==undefined&&mainRecid!==recid){t397_alltabs_updateContent(recid);t397_updateSelect(recid);el.find('.t397__tab:nth-child(1)').trigger('click')}}})}else{active.forEach(function(recid){var el=$('#rec'+recid);el.attr('data-animationappear','off');el.addClass('t395__off')})}
off.forEach(function(recid){if(recid!==''){var el=$('#rec'+recid);var recordType=el.attr('data-record-type');el.attr('data-connect-with-tab','yes');el.attr('data-animationappear','off');el.addClass('t395__off');if(recordType==='395'&&mainRecid!==recid){t395_alltabs_updateContent(recid);t395_updateSelect(recid);el.find('.t395__tab:nth-child(1)').trigger('click')}
if(recordType==='397'&&t397_alltabs_updateContent!==undefined&&t397_updateSelect!==undefined&&mainRecid!==recid){t397_alltabs_updateContent(recid);t397_updateSelect(recid);el.find('.t397__tab:nth-child(1)').trigger('click')}}})}}
function t395_updateContentBySelect(recid){var el=$('#rec'+recid);el.find(".t395__select").change(function(){var select_val=el.find(".t395__select").val();var tab_index=el.find(".t395__tab[data-tab-rec-ids='"+select_val+"']");tab_index.trigger('click')})}
function t395_updateSelect(recid){var el=$('#rec'+recid);var current_tab=el.find(".t395__tab_active").attr('data-tab-rec-ids');var el_select=el.find(".t395__select");el_select.val(current_tab)}
function t395_startUpdateLazyLoad($this){var rec_ids=$this.attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);var video=rec_el.find('.t-video-lazyload');if(video.length>0){t395_updateVideoLazyLoad(video)}})}
function t395_updateVideoLazyLoad(video){setTimeout(function(){video.each(function(){var div=$(this);if(!div.hasClass('t-video__isload')){var height=div.attr('data-videolazy-height')?$(this).attr('data-videolazy-height'):'100%';if(height.indexOf('vh')!=-1){height='100%'}
var videoId=div.attr('data-videolazy-id').trim();var blockId=div.attr('data-blocklazy-id')||'';if(typeof div.attr('data-videolazy-two-id')!='undefined'){var videoTwoId='_'+div.attr('data-videolazy-two-id')+'_'}else{var videoTwoId=''}
if(div.attr('data-videolazy-type')=='youtube'){div.find('iframe').remove();div.prepend('<iframe id="youtubeiframe'+videoTwoId+blockId+'" width="100%" height="'+height+'" src="//www.youtube.com/embed/'+videoId+'?rel=0&fmt=18&html5=1&showinfo=0" frameborder="0" allowfullscreen></iframe>')}}
div.addClass('t-video__isload')})},2)}
function t395_scrollToTabs(recid){var el=$('#rec'+recid);var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');var tabIndexNumberStart=curUrl.indexOf('tab/');el.find('.t395__wrapper_mobile .t395__select option:eq(0)').prop('selected',!1);if(tabIndexNumber!==-1){var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec==recid){var tabBlock=$('#rec'+tabRec).find('.t395');var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);el.find('.t395__tab').removeClass('t395__tab_active');el.find('.t395__tab:eq('+(tabNumber-1)+')').addClass('t395__tab_active');el.find('.t395__wrapper_mobile .t395__select option:eq('+(tabNumber-1)+')').prop('selected',!0);var targetOffset=tabBlock.offset().top;var target=targetOffset;if($(window).width()>960){target=targetOffset-200}else{target=targetOffset-100}
$('html, body').animate({scrollTop:target},300)}}}
function t395_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!=-1){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}}}
function t396_init(recid){var data='';var res=t396_detectResolution();var ab=$('#rec'+recid).find('.t396__artboard');window.tn_window_width=$(window).width();window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;t396_initTNobj();t396_switchResolution(res);t396_updateTNobj();t396_artboard_build(data,recid);$(window).resize(function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if($isMobile){var ww=$(window).width();if(ww!=window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});$(window).on("orientationchange",function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});$(window).on('load',function(){t396_allelems__renderView(ab);if(typeof t_lazyload_update==='function'&&ab.css('overflow')==='auto'){ab.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&ab.css('overflow')==='visible'){ab.css('overflow','hidden');setTimeout(function(){ab.css('overflow','visible')},1)}});var rec=$('#rec'+recid);if(rec.attr('data-connect-with-tab')=='yes'){rec.find('.t396').bind('displayChanged',function(){var ab=rec.find('.t396__artboard');t396_allelems__renderView(ab)})}
if(isSafari)rec.find('.t396').addClass('t396_safari');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_getRotateValue(matrix){var values=matrix.split('(')[1].split(')')[0].split(',');var a=values[0];var b=values[1];var c=values[2];var d=values[3];var scale=Math.sqrt(a*a+b*b);var sin=b/scale;var angle=Math.round(Math.atan2(b,a)*(180/Math.PI));return angle}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search("Firefox")!==-1;var isOpera=(!!window.opr&&!!opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var res=t396_detectResolution();var rec=$('#rec'+recid);var $ab=rec.find('.t396__artboard');var abWidth=$ab.width();var updatedBlockHeight=Math.floor($ab.height()*window.tn_scale_factor);var ab_height_vh=t396_ab__getFieldValue($ab,'height_vh');window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;if(ab_height_vh!=''){var ab_min_height=t396_ab__getFieldValue($ab,'height');var ab_max_height=t396_ab__getHeight($ab);var scaledMinHeight=ab_min_height*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=ab_max_height)?scaledMinHeight:ab_max_height}
$ab.addClass('t396__artboard_scale');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'<style>';$ab.append(styleStr);rec.find('.t396__elem').each(function(){var $el=$(this);var containerProp=t396_elem__getFieldValue($el,'container');if(containerProp==='grid'){if(isOnlyScalable){var scaleProp='scale('+window.tn_scale_factor+')';$el.find('.tn-atom').wrap("<div class='tn-atom__scale-wrapper' style='transform: scale("+window.tn_scale_factor+");'></div>")}else{$el.css('zoom',window.tn_scale_factor);if($el.attr('data-elem-type')==='text'&&res<1200)$el.find('.tn-atom').css('-webkit-text-size-adjust','auto');$el.find('.tn-atom').css('transform-origin','center')}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var ww;var rec=$('#rec'+recid);if($isMobile){ww=$(window).width()}else{ww=window.innerWidth}
var res=t396_detectResolution();rec.find('.t396__scale-style').remove();if(!isOnlyScalable){rec.find('.t396__elem').css('zoom','');rec.find('.t396__elem .tn-atom').css('transform-origin','')}else{rec.find('.tn-atom').each(function(){if($(this).closest('.tn-atom__scale-wrapper').length){$(this).unwrap('.tn-atom__scale-wrapper')}})}
var ab=rec.find('.t396__artboard');var abWidth=ab.width();window.tn_window_width=ww;window.tn_scale_factor=Math.round((window.tn_window_width/res)*100)/100;window.tn_scale_offset=(abWidth*window.tn_scale_factor-abWidth)/2;t396_switchResolution(res);t396_updateTNobj();t396_ab__renderView(ab);t396_allelems__renderView(ab);var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_detectResolution(){var ww;if($isMobile){ww=$(window).width()}else{ww=window.innerWidth}
var res;res=1200;if(ww<1200){res=960}
if(ww<960){res=640}
if(ww<640){res=480}
if(ww<480){res=320}
return(res)}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=["320","480","640","960","1200"];window.tn.canvas_max_sizes=["480","640","960","1200",""];window.tn.ab_fields=["height","width","bgcolor","bgimg","bgattachment","bgposition","filteropacity","filtercolor","filteropacity2","filtercolor2","height_vh","valign"]}
function t396_updateTNobj(){tn_console('func: updateTNobj');if(typeof window.zero_window_width_hook!='undefined'&&window.zero_window_width_hook=='allrecords'&&$('#allrecords').length){window.tn.window_width=parseInt($('#allrecords').width())}else{window.tn.window_width=parseInt($(window).width())}
if($isMobile){window.tn.window_height=parseInt($(window).height())}else{window.tn.window_height=parseInt(window.innerHeight)}
if(window.tn.curResolution==1200){window.tn.canvas_min_width=1200;window.tn.canvas_max_width=window.tn.window_width}
if(window.tn.curResolution==960){window.tn.canvas_min_width=960;window.tn.canvas_max_width=1200}
if(window.tn.curResolution==640){window.tn.canvas_min_width=640;window.tn.canvas_max_width=960}
if(window.tn.curResolution==480){window.tn.canvas_min_width=480;window.tn.canvas_max_width=640}
if(window.tn.curResolution==320){window.tn.canvas_min_width=320;window.tn.canvas_max_width=480}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=parseFloat((window.tn.window_width-window.tn.grid_width)/2)}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId="Don't call this twice without a uniqueId"}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(res,resmax){tn_console('func: switchResolution');if(typeof resmax=='undefined'){if(res==1200)resmax='';if(res==960)resmax=1200;if(res==640)resmax=960;if(res==480)resmax=640;if(res==320)resmax=480}
window.tn.curResolution=res;window.tn.curResolution_max=resmax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var ab=$('#rec'+recid).find('.t396__artboard');t396_ab__renderView(ab);ab.find('.tn-elem').each(function(){var item=$(this);if(item.attr('data-elem-type')=='text'){t396_addText(ab,item)}
if(item.attr('data-elem-type')=='image'){t396_addImage(ab,item)}
if(item.attr('data-elem-type')=='shape'){t396_addShape(ab,item)}
if(item.attr('data-elem-type')=='button'){t396_addButton(ab,item)}
if(item.attr('data-elem-type')=='video'){t396_addVideo(ab,item)}
if(item.attr('data-elem-type')=='html'){t396_addHtml(ab,item)}
if(item.attr('data-elem-type')=='tooltip'){t396_addTooltip(ab,item)}
if(item.attr('data-elem-type')=='form'){t396_addForm(ab,item)}
if(item.attr('data-elem-type')=='gallery'){t396_addGallery(ab,item)}});$('#rec'+recid).find('.t396__artboard').removeClass('rendering').addClass('rendered');var overflowValue=ab.attr('data-artboard-ovrflw');if(overflowValue==='visible'||overflowValue==='visibleX'){$('#allrecords').css('overflow','hidden')}
if($isMobile){$('#rec'+recid).append('<style>@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}</style>')}}
function t396_ab__renderView(ab){var fields=window.tn.ab_fields;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(ab,fields[i])}
var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(isScaled&&!isTildaModeEdit&&ab_height_vh!='')var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor;var offset_top=0;if(ab_min_height==ab_max_height||(scaledMinHeight&&scaledMinHeight>=ab_max_height)){offset_top=0}else{var ab_valign=t396_ab__getFieldValue(ab,'valign');if(ab_valign=='top'){offset_top=0}else if(ab_valign=='center'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)/2).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)/2).toFixed(1)}}else if(ab_valign=='bottom'){if(scaledMinHeight){offset_top=parseFloat((ab_max_height-scaledMinHeight)).toFixed(1)}else{offset_top=parseFloat((ab_max_height-ab_min_height)).toFixed(1)}}else if(ab_valign=='stretch'){offset_top=0;ab_min_height=ab_max_height}else{offset_top=0}}
ab.attr('data-artboard-proxy-min-offset-top',offset_top);ab.attr('data-artboard-proxy-min-height',ab_min_height);ab.attr('data-artboard-proxy-max-height',ab_max_height);var filter=ab.find('.t396__filter');var carrier=ab.find('.t396__carrier');var abHeightVh=t396_ab__getFieldValue(ab,'height_vh');abHeightVh=parseFloat(abHeightVh);if(window.isMobile&&abHeightVh){var height=document.documentElement.clientHeight*parseFloat(abHeightVh/100);ab.css('height',height);filter.css('height',height);carrier.css('height',height)}}
function t396_addText(ab,el){tn_console('func: addText');var fields_str='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addImage(ab,el){tn_console('func: addImage');var fields_str='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);el.find('img').on("load",function(){t396_elem__renderViewOneField(el,'top');if(typeof $(this).attr('src')!='undefined'&&$(this).attr('src')!=''){setTimeout(function(){t396_elem__renderViewOneField(el,'top')},2000)}}).each(function(){if(this.complete)$(this).trigger('load')});el.find('img').on('tuwidget_done',function(e,file){t396_elem__renderViewOneField(el,'top')})}
function t396_addShape(ab,el){tn_console('func: addShape');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addButton(ab,el){tn_console('func: addButton');var fields_str='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);return(el)}
function t396_addVideo(ab,el){tn_console('func: addVideo');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var viel=el.find('.tn-atom__videoiframe');var viatel=el.find('.tn-atom');viatel.css('background-color','#000');var vihascover=viatel.attr('data-atom-video-has-cover');if(typeof vihascover=='undefined'){vihascover=''}
if(vihascover=='y'){viatel.click(function(){var viifel=viel.find('iframe');if(viifel.length){var foo=viifel.attr('data-original');viifel.attr('src',foo)}
viatel.css('background-image','none');viatel.find('.tn-atom__video-play-link').css('display','none')})}
var autoplay=t396_elem__getFieldValue(el,'autoplay');var showinfo=t396_elem__getFieldValue(el,'showinfo');var loop=t396_elem__getFieldValue(el,'loop');var mute=t396_elem__getFieldValue(el,'mute');var startsec=t396_elem__getFieldValue(el,'startsec');var endsec=t396_elem__getFieldValue(el,'endsec');var tmode=$('#allrecords').attr('data-tilda-mode');var url='';var viyid=viel.attr('data-youtubeid');if(typeof viyid!='undefined'&&viyid!=''){url='//youtube.com/embed/';url+=viyid+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo=='y'?'1':'0');if(loop=='y'){url+='&loop=1&playlist='+viyid}
if(startsec>0){url+='&start='+startsec}
if(endsec>0){url+='&end='+endsec}
if(mute=='y'){url+='&mute=1'}
if(vihascover=='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
viel.html('<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>');if(autoplay=='y'&&mute=='y'&&window.lazy=='y'){el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}
if(autoplay=='y'&&mute=='y'){viatel.trigger('click')}}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>')}}}
var vivid=viel.attr('data-vimeoid');if(typeof vivid!='undefined'&&vivid>0){url='//player.vimeo.com/video/';url+=vivid+'?color=ffffff&badge=0';if(showinfo=='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop=='y'){url+='&loop=1'}
if(mute=='y'){url+='&muted=1'}
if(vihascover=='y'){url+='&autoplay=1';viel.html('<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}else{if(typeof tmode!='undefined'&&tmode=='edit'){}else{if(autoplay=='y'){url+='&autoplay=1'}}
if(window.lazy=='y'){viel.html('<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>');el.append('<script>lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});<\/script>')}else{viel.html('<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>')}}}}
function t396_addHtml(ab,el){tn_console('func: addHtml');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addTooltip(ab,el){tn_console('func: addTooltip');var fields_str='width,height,top,left,';fields_str+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el);var pinEl=el.find('.tn-atom__pin');var tipEl=el.find('.tn-atom__tip');var tipopen=el.attr('data-field-tipopen-value');if(isMobile||(typeof tipopen!='undefined'&&tipopen=='click')){t396_setUpTooltip_mobile(el,pinEl,tipEl)}else{t396_setUpTooltip_desktop(el,pinEl,tipEl)}
setTimeout(function(){$('.tn-atom__tip-img').each(function(){var foo=$(this).attr('data-tipimg-original');if(typeof foo!='undefined'&&foo!=''){$(this).attr('src',foo)}})},3000)}
function t396_addForm(ab,el){tn_console('func: addForm');var fields_str='width,top,left,';fields_str+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_addGallery(ab,el){tn_console('func: addForm');var fields_str='width,height,top,left,';fields_str+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';var fields=fields_str.split(',');el.attr('data-fields',fields_str);t396_elem__renderView(el)}
function t396_elem__setFieldValue(el,prop,val,flag_render,flag_updateui,res){if(res=='')res=window.tn.curResolution;if(res<1200&&prop!='zindex'){el.attr('data-field-'+prop+'-res-'+res+'-value',val)}else{el.attr('data-field-'+prop+'-value',val)}
if(flag_render=='render')elem__renderViewOneField(el,prop);if(flag_updateui=='updateui')panelSettings__updateUi(el,prop,val)}
function t396_elem__getFieldValue(el,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}
if(res==640){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}
if(res==480){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}
if(res==320){r=el.attr('data-field-'+prop+'-res-320-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-480-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-640-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-res-960-value');if(typeof r=='undefined'){r=el.attr('data-field-'+prop+'-value')}}}}}}else{r=el.attr('data-field-'+prop+'-value')}
return(r)}
function t396_elem__renderView(el){tn_console('func: elem__renderView');var fields=el.attr('data-fields');if(!fields){return!1}
fields=fields.split(',');for(var i=0;i<fields.length;i++){t396_elem__renderViewOneField(el,fields[i])}}
function t396_elem__renderViewOneField(el,field){var value=t396_elem__getFieldValue(el,field);if(field=='left'){value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('left',parseFloat(value).toFixed(1)+'px')}
if(field=='top'){var ab=el.parents('.t396__artboard');value=t396_elem__convertPosition__Local__toAbsolute(el,field,value);el.css('top',parseFloat(value).toFixed(1)+'px')}
if(field=='width'){value=t396_elem__getWidth(el,value);el.css('width',parseFloat(value).toFixed(1)+'px');var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){var pinSvgIcon=el.find('.tn-atom__pin-icon');if(pinSvgIcon.length>0){var pinSize=parseFloat(value).toFixed(1)+'px';pinSvgIcon.css({'width':pinSize,'height':pinSize})}
el.css('height',parseInt(value).toFixed(1)+'px')}
if(eltype=='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('width',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('width',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('width',parseFloat(value).toFixed(1)+'px')}}
if(field=='height'){var eltype=el.attr('data-elem-type');if(eltype=='tooltip'){return}
value=t396_elem__getHeight(el,value);el.css('height',parseFloat(value).toFixed(1)+'px');if(eltype==='gallery'){var borderWidth=t396_elem__getFieldValue(el,'borderwidth');var borderStyle=t396_elem__getFieldValue(el,'borderstyle');if(borderStyle=='none'||typeof borderStyle=='undefined'||typeof borderWidth=='undefined'||borderWidth=='')borderWidth=0;value=value*1-borderWidth*2;el.css('height',parseFloat(value).toFixed(1)+'px');el.find('.tn-atom__slds-img').css('height',parseFloat(value).toFixed(1)+'px');el.find('.t-slds__main').css('height',parseFloat(value).toFixed(1)+'px')}}
if(field=='container'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='width'||field=='height'||field=='fontsize'||field=='fontfamily'||field=='letterspacing'||field=='fontweight'||field=='img'){t396_elem__renderViewOneField(el,'left');t396_elem__renderViewOneField(el,'top')}
if(field=='inputs'){value=el.find('.tn-atom__inputs-textarea').val();try{t_zeroForms__renderForm(el,value)}catch(err){}}}
function t396_elem__convertPosition__Local__toAbsolute(el,field,value){var ab=el.parents('.t396__artboard');var blockVAlign=t396_ab__getFieldValue(ab,'valign');var isScaled=t396_ab__getFieldValue(ab,'upscale')==='window';var isTildaModeEdit=$('#allrecords').attr('data-tilda-mode')=='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var el_axisy=t396_elem__getFieldValue(el,'axisy');value=parseInt(value);if(field=='left'){var el_container,offset_left,el_container_width,el_width;var container=t396_elem__getFieldValue(el,'container');if(container==='grid'){el_container='grid';offset_left=window.tn.grid_offset_left;el_container_width=window.tn.grid_width}else{el_container='window';offset_left=0;el_container_width=window.tn.window_width}
var el_leftunits=t396_elem__getFieldValue(el,'leftunits');if(el_leftunits==='%'){value=t396_roundFloat(el_container_width*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offset_left+value}
var el_axisx=t396_elem__getFieldValue(el,'axisx');if(el_axisx==='center'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width/2-el_width/2+value}
if(el_axisx==='right'){el_width=t396_elem__getWidth(el);if(isScaledElement&&el_container!=='window'){el_container_width*=window.tn_scale_factor;el_width*=window.tn_scale_factor}
value=el_container_width-el_width+value}
if(isScaledElement&&el_container!=='window'){var elementWidth=t396_elem__getWidth(el);value=value+(elementWidth*window.tn_scale_factor-elementWidth)/2}}
if(field==='top'){var el_container,offset_top,el_container_height,el_height;var ab=el.parent();var container=t396_elem__getFieldValue(el,'container');var getElementHeight=function(el){var height=t396_elem__getHeight(el);if(el.attr('data-elem-type')==='image'){var width=t396_elem__getWidth(el);var fileWidth=t396_elem__getFieldValue(el,'filewidth');var fileHeight=t396_elem__getFieldValue(el,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);height=width/ratio}}
return height}
if(container==='grid'){el_container='grid';offset_top=parseFloat(ab.attr('data-artboard-proxy-min-offset-top'));el_container_height=parseFloat(ab.attr('data-artboard-proxy-min-height'))}else{el_container='window';offset_top=0;el_container_height=parseFloat(ab.attr('data-artboard-proxy-max-height'))}
var el_topunits=t396_elem__getFieldValue(el,'topunits');if(el_topunits==='%'){value=(el_container_height*(value/100))}
if(isScaledElement&&el_container!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&el_container!=='window'){offset_top=blockVAlign==='stretch'?0:(offset_top/window.tn_scale_factor)}
value=offset_top+value;var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');var ab_min_height=t396_ab__getFieldValue(ab,'height');var ab_max_height=t396_ab__getHeight(ab);if(isScaled&&!isTildaModeEdit&&ab_height_vh!=''){var scaledMinHeight=parseInt(ab_min_height,10)*window.tn_scale_factor}
if(el_axisy==='center'){el_height=getElementHeight(el);if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height/2-el_height/2+value}
if(el_axisy==='bottom'){el_height=getElementHeight(el);if(isScaledElement&&el_container!=='window'){if(blockVAlign!=='stretch'){el_container_height=el_container_height*window.tn_scale_factor}else{if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}}
el_height*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&el_container!=='window'&&blockVAlign==='stretch'){if(scaledMinHeight){el_container_height=scaledMinHeight>ab_max_height?scaledMinHeight:ab_max_height}else{el_container_height=ab.height()}
el_container_height=el_container_height/window.tn_scale_factor}
value=el_container_height-el_height+value}
if(isScaledElement&&el_container!=='window'){var elementHeight=getElementHeight(el);value=value+(elementHeight*window.tn_scale_factor-elementHeight)/2}}
return(value)}
function t396_ab__setFieldValue(ab,prop,val,res){if(res=='')res=window.tn.curResolution;if(res<1200){ab.attr('data-artboard-'+prop+'-res-'+res,val)}else{ab.attr('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(ab,prop){var res=window.tn.curResolution;var r;if(res<1200){if(res==960){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}
if(res==640){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}
if(res==480){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}
if(res==320){r=ab.attr('data-artboard-'+prop+'-res-320');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-480');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-640');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'-res-960');if(typeof r=='undefined'){r=ab.attr('data-artboard-'+prop+'')}}}}}}else{r=ab.attr('data-artboard-'+prop)}
return(r)}
function t396_ab__renderViewOneField(ab,field){var value=t396_ab__getFieldValue(ab,field)}
function t396_allelems__renderView(ab){tn_console('func: allelems__renderView: abid:'+ab.attr('data-artboard-recid'));ab.find(".tn-elem").each(function(){t396_elem__renderView($(this))})}
function t396_ab__filterUpdate(ab){var filter=ab.find('.t396__filter');var c1=filter.attr('data-filtercolor-rgb');var c2=filter.attr('data-filtercolor2-rgb');var o1=filter.attr('data-filteropacity');var o2=filter.attr('data-filteropacity2');if((typeof c2=='undefined'||c2=='')&&(typeof c1!='undefined'&&c1!='')){filter.css("background-color","rgba("+c1+","+o1+")")}else if((typeof c1=='undefined'||c1=='')&&(typeof c2!='undefined'&&c2!='')){filter.css("background-color","rgba("+c2+","+o2+")")}else if(typeof c1!='undefined'&&typeof c2!='undefined'&&c1!=''&&c2!=''){filter.css({background:"-webkit-gradient(linear, left top, left bottom, from(rgba("+c1+","+o1+")), to(rgba("+c2+","+o2+")) )"})}else{filter.css("background-color",'transparent')}}
function t396_ab__getHeight(ab,ab_height){if(typeof ab_height=='undefined')ab_height=t396_ab__getFieldValue(ab,'height');ab_height=parseFloat(ab_height);var ab_height_vh=t396_ab__getFieldValue(ab,'height_vh');if(ab_height_vh!=''){ab_height_vh=parseFloat(ab_height_vh);if(isNaN(ab_height_vh)===!1){var ab_height_vh_px=parseFloat(window.tn.window_height*parseFloat(ab_height_vh/100));if(ab_height<ab_height_vh_px){ab_height=ab_height_vh_px}}}
return(ab_height)}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(el,value){if(typeof value=='undefined')value=parseFloat(t396_elem__getFieldValue(el,'width'));var el_widthunits=t396_elem__getFieldValue(el,'widthunits');if(el_widthunits=='%'){var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(window.tn.window_width*parseFloat(parseInt(value)/100))}else{value=parseFloat(window.tn.grid_width*parseFloat(parseInt(value)/100))}}
return(value)}
function t396_elem__getHeight(el,value){if(typeof value=='undefined')value=t396_elem__getFieldValue(el,'height');value=parseFloat(value);if(el.attr('data-elem-type')=='shape'||el.attr('data-elem-type')=='video'||el.attr('data-elem-type')=='html'||el.attr('data-elem-type')=='gallery'){var el_heightunits=t396_elem__getFieldValue(el,'heightunits');if(el_heightunits=='%'){var ab=el.parent();var ab_min_height=parseFloat(ab.attr('data-artboard-proxy-min-height'));var ab_max_height=parseFloat(ab.attr('data-artboard-proxy-max-height'));var el_container=t396_elem__getFieldValue(el,'container');if(el_container=='window'){value=parseFloat(ab_max_height*parseFloat(value/100))}else{value=parseFloat(ab_min_height*parseFloat(value/100))}}}else if(el.attr('data-elem-type')=='button'){value=value}else{value=parseFloat(el.innerHeight())}
return(value)}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(window.tn_comments==1)console.log(str)}
function t396_setUpTooltip_desktop(el,pinEl,tipEl){var timer;pinEl.mouseover(function(){$('.tn-atom__tip_visible').each(function(){var thisTipEl=$(this).parents('.t396__elem');if(thisTipEl.attr('data-elem-id')!=el.attr('data-elem-id')){t396_hideTooltip(thisTipEl,$(this))}});clearTimeout(timer);if(tipEl.css('display')=='block'){return}
t396_showTooltip(el,tipEl)});pinEl.mouseout(function(){timer=setTimeout(function(){t396_hideTooltip(el,tipEl)},300)})}
function t396_setUpTooltip_mobile(el,pinEl,tipEl){pinEl.on('click',function(e){if(tipEl.css('display')=='block'&&$(e.target).hasClass("tn-atom__pin")){t396_hideTooltip(el,tipEl)}else{t396_showTooltip(el,tipEl)}});var id=el.attr("data-elem-id");$(document).click(function(e){var isInsideTooltip=($(e.target).hasClass("tn-atom__pin")||$(e.target).parents(".tn-atom__pin").length>0);if(isInsideTooltip){var clickedPinId=$(e.target).parents(".t396__elem").attr("data-elem-id");if(clickedPinId==id){return}}
t396_hideTooltip(el,tipEl)})}
function t396_hideTooltip(el,tipEl){tipEl.css('display','');tipEl.css({"left":"","transform":"","right":""});tipEl.removeClass('tn-atom__tip_visible');el.css('z-index','')}
function t396_showTooltip(el,tipEl){var pos=el.attr("data-field-tipposition-value");if(typeof pos=='undefined'||pos==''){pos='top'};var elSize=el.height();var elTop=el.offset().top;var elBottom=elTop+elSize;var elLeft=el.offset().left;var elRight=el.offset().left+elSize;var winTop=$(window).scrollTop();var winWidth=$(window).width();var winBottom=winTop+$(window).height();var tipElHeight=tipEl.outerHeight();var tipElWidth=tipEl.outerWidth();var padd=15;if(pos=='right'||pos=='left'){var tipElRight=elRight+padd+tipElWidth;var tipElLeft=elLeft-padd-tipElWidth;if((pos=='right'&&tipElRight>winWidth)||(pos=='left'&&tipElLeft<0)){pos='top'}}
if(pos=='top'||pos=='bottom'){var tipElRight=elRight+(tipElWidth/2-elSize/2);var tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padd);tipEl.css({"left":"auto","transform":"none","right":rightOffset+"px"})}
if(tipElLeft<0){var leftOffset=-(elLeft-padd);tipEl.css({"left":leftOffset+"px","transform":"none"})}}
if(pos=='top'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos=='bottom'){var tipElTop=elTop-padd-tipElHeight;var tipElBottom=elBottom+padd+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
tipEl.attr('data-tip-pos',pos);tipEl.css('display','block');tipEl.addClass('tn-atom__tip_visible');el.css('z-index','1000')}
function t396_hex2rgba(hexStr,opacity){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t401_showMore(recid){var el=$('#rec'+recid).find(".t401");el.find(".t401__col").hide();var cards_size=el.find(".t401__col").size();var cards_count=parseInt(el.attr("data-show-count"));var x=cards_count;var y=cards_count;el.find('.t401__col:lt('+x+')').show();el.find('.t401__showmore').click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t401__col:lt('+x+')').show();if(x==cards_size){el.find('.t401__showmore').hide()}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t450_showMenu(recid){var el=$('#rec'+recid);$('body').addClass('t450__body_menushowed');el.find('.t450').addClass('t450__menu_show');el.find('.t450__overlay').addClass('t450__menu_show');$('.t450').bind('clickedAnchorInTooltipMenu',function(){t450_closeMenu()});el.find('.t450__overlay, .t450__close, a[href*="#"]').click(function(){var url=$(this).attr('href');if(typeof url!='undefined'&&url!=''&&(url.substring(0,7)=='#price:'||url.substring(0,9)=='#submenu:')){return}
if($(this).is('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link')){return}
t450_closeMenu()});$(document).keydown(function(e){if(e.keyCode===27){$('body').removeClass('t390__body_popupshowed');$('.t390').removeClass('t390__popup_show')}});el.find('.t-menu__link-item').each(function(){var $this=$(this);if($this.hasClass('t966__tm-link')){$this.on('click',function(){setTimeout(function(){t450_checkSize(recid)},300)})}
if($this.hasClass('t978__tm-link')){$this.on('click',function(){t450_checkSize(recid);el.find(".t978__menu-link").on('click',function(){t450_checkSize(recid)})})}});t450_highlight()}
function t450_closeMenu(){$('body').removeClass('t450__body_menushowed');$('.t450').removeClass('t450__menu_show');$('.t450__overlay').removeClass('t450__menu_show')}
function t450_checkSize(recid){var el=$('#rec'+recid).find('.t450');var windowheight=$(window).height()-80;setTimeout(function(){var contentheight=el.find(".t450__top").height()+el.find(".t450__rightside").height();if(contentheight>windowheight){el.addClass('t450__overflowed');el.find(".t450__container").css('height','auto')}else{el.removeClass('t450__overflowed');el.find(".t450__container").css('height','')}})}
function t450_appearMenu(recid){var el=$('#rec'+recid);var burger=el.find(".t450__burger_container");burger.each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t450__beforeready')){el.finish();el.removeClass("t450__beforeready")}}else{el.stop();el.addClass("t450__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t450__beforeready')){el.finish();el.addClass("t450__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t450__beforeready")}}else{el.stop();el.removeClass("t450__beforeready")}}}})}
function t450_initMenu(recid){var el=$('#rec'+recid).find('.t450');var hook=el.attr('data-tooltip-hook');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid);e.preventDefault()})}
$('#rec'+recid).find('.t450__burger_container').click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid)});if(window.isMobile){$('#rec'+recid).find('.t-menu__link-item').each(function(){var $this=$(this);if($this.hasClass('t450__link-item_submenu')){$this.on('click',function(){t450_checkSize(recid)})}})}
$(window).on('resize',function(){t450_checkSize(recid)})}
function t450_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t450__menu a").removeClass("t-active");$(".t450__menu a[href='"+url+"']").addClass("t-active");$(".t450__menu a[href='"+url+"/']").addClass("t-active");$(".t450__menu a[href='"+pathname+"']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"']").addClass("t-active");$(".t450__menu a[href='"+pathname+"/']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"/']").addClass("t-active");if(hash!==""){$(".t450__menu a[href='"+hash+"']").addClass("t-active")}}
function t599_init(recid){var el=$('#rec'+recid);if(el.find('.t599__title').length){t599_equalHeight(el.find('.t599__title'))}
if(el.find('.t599__descr').length){t599_equalHeight(el.find('.t599__descr'))}
if(el.find('.t599__price').length){t599_equalHeight(el.find('.t599__price'))}
if(el.find('.t599__subtitle').length){t599_equalHeight(el.find('.t599__subtitle'))}};function t599_equalHeight(element){var highestBox=0;element.css('height','');element.each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){element.css('height',highestBox)}else{element.css('height','')}}
function t651_initPopup(recid){if(window.$isMobile){if($('#rec'+recid+' .t651__phone').length==0){return}
t651_phone=$('#rec'+recid+' .t651__phone').text().replace(/\s+/g,'');$('#rec'+recid+' .t651__btn').click(function(){window.location.href="tel:"+t651_phone;$('.t651__btn_wrapper').removeClass('t651__btn_animate');$('.t651__btn-text').css('display','none')});return}
$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t651__popup'),analitics=el.attr('data-track-popup'),hook="TildaCallBackWidget"+recid,obj=$('#rec'+recid+' .t651__btn');obj.click(function(e){if(obj.hasClass("t651__btn_active")){t651_closePopup();return}
obj.addClass("t651__btn_active");t651_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}
function t651_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t651__popup');$('.t651__btn_wrapper').removeClass('t651__btn_animate');$('.t651__btn-text').css('display','none');popup.css('display','block');setTimeout(function(){popup.addClass('t651__popup_show')},50);$(document).keydown(function(e){if(e.keyCode==27){t651_closePopup()}})}
function t651_closePopup(){$('.t651__btn').removeClass('t651__btn_active');$('.t651__popup').removeClass('t651__popup_show');setTimeout(function(){$('.t651__popup').not('.t651__popup_show').css('display','none')},300)}
function t651_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t668_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t668__header");var accordion=el.find('.t668__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t668__opened").next().slideUp()}
$(this).toggleClass("t668__opened");$(this).next().slideToggle();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t694_init(recid){var el=$('#rec'+recid);t694_setHeight(recid);$(window).resize(t_throttle(function(){t694_setHeight(recid)}));el.find('.t694').bind('displayChanged',t_throttle(function(){t694_setHeight(recid)}));setTimeout(function(){t694_setHeight(recid)},500)}
function t694_setHeight(recid){var el=$('#rec'+recid+' .t694');var t694_ratio=el.attr('data-tile-ratio');var t694_ratioHeight=el.find('.t694__col').width()*t694_ratio;if($(window).width()>=768){el.find('.t694__row').each(function(){var t694_largestHeight=0;$(this).find('.t694__table').each(function(){var t694_curCol=$(this),t694_curColHeight=t694_curCol.find(".t694__textwrapper").outerHeight();if($(this).find(".t694__cell").hasClass("t694__button-bottom")){t694_curColHeight+=t694_curCol.find(".t694__button-container").outerHeight()}
if(t694_curColHeight>t694_largestHeight){t694_largestHeight=t694_curColHeight}});if(t694_largestHeight>t694_ratioHeight){$(this).find('.t694__table').css('height',t694_largestHeight)}else{if($(this).find('.t694__table').css('height')!=''){$(this).find('.t694__table').css('height','')}}})}else{el.find('.t694__table').css('height','')}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');el.bind('scroll',t_throttle(function(){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}));if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop");window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var rec=$('#rec'+recid);var popup=rec.find('.t-popup');popup.css('display','block');var $range=rec.find('.t-range');$range.trigger('popupOpened');var range=$range.get(0);if(range){var triggerChangeEvent;if(/msie|trident/.test(navigator.userAgent)){triggerChangeEvent=document.createEvent('Event');triggerChangeEvent.initEvent('popupOpened',!0,!1)}else{triggerChangeEvent=new Event('popupOpened')}
range.dispatchEvent(triggerChangeEvent)}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
rec.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t702_closePopup(recid)}});rec.find('.t-popup__close').click(function(e){t702_closePopup(recid)});rec.find('.t-submit[href*="#"]').click(function(e){if($('body').hasClass('t-body_scroll-locked')){$('body').removeClass('t-body_scroll-locked')}});rec.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recid);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup(recid)}})}
function t702_closePopup(recid){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');$('#rec'+recid+' .t-popup').removeClass('t-popup_show');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t706_onSuccessCallback(t706_form){$(".t706__cartwin-products").slideUp(10,function(){});$(".t706__cartwin-bottom").slideUp(10,function(){});$(".t706 .t-form__inputsbox").slideUp(700,function(){});try{tcart__unlockScroll()}catch(e){}}
function t764_init(recid){var el=$('#rec'+recid);t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)});t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var sliderWrapper=el.find('.t-slds__items-wrapper');var sliderWidth=el.find('.t-slds__container').width();var pos=parseFloat(sliderWrapper.attr('data-slider-pos'),10);sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)});el.find('.t764').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}
function t794_init(recid){var hook=$('#rec'+recid+' .t794').attr('data-tooltip-hook');if(typeof hook==="undefined"||hook===""){return}
var hookLinks=$('a[href="'+hook+'"][data-submenu-disallowed!="yes"]');hookLinks.addClass('t794__tm-link');hookLinks.attr('data-tooltip-menu-id',recid);t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t794_highlight()}
function t794_setUpMenu(recid,hookLinks){var submenu=$('#rec'+recid+' .t794__tooltip-menu');var content=submenu.find('t794__content');if(window.isMobile){t794_setUpMenu_mobile(recid,hookLinks,submenu)}else{t794_setUpMenu_desktop(recid,hookLinks,submenu)}
$(window).bind('scroll',t_throttle(function(){content.hover(function(){},function(){if(submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})},300));$('.t794__tooltip-menu a[href*="#"]').click(function(){t794_hideSubmenu(submenu);$('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466').trigger('clickedAnchorInTooltipMenu');$('.t794__tooltip-menu a[href*="#"]').removeClass('t-active');$(this).addClass('t-active')})}
function t794_setUpMenu_mobile(recid,hookLinks,submenu){var vIndent=$('#rec'+recid+' .t794').attr('data-tooltip-margin');hookLinks.on('click',function(e){if(submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}else{var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)}
e.preventDefault()});$(document).click(function(e){var isInsideSubmenu=($(e.target).hasClass('t794__tooltip-menu')||$(e.target).parents('.t794__tooltip-menu').length>0);var isAnchor=($(e.target).hasClass('t794__tm-link')||$(e.target).parents('.t794__tm-link').length>0);if(isAnchor){var curAnchor;if($(e.target).hasClass('t794__tm-link')){curAnchor=$(e.target)}else{curAnchor=$(e.target).parents('.t794__tm-link')}
if(curAnchor.attr('data-tooltip-menu-id')!=recid&&submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}}
if(!isInsideSubmenu&&!isAnchor&&submenu.hasClass('t794__tooltip-menu_show')){t794_hideSubmenu(submenu)}})}
function t794_setUpMenu_desktop(recid,hookLinks,submenu){var vIndent=$('#rec'+recid+' .t794').attr('data-tooltip-margin');var timer;hookLinks.add(submenu).on('mouseover',function(){if($(this).hasClass('t794__tooltip-menu')&&!$(this).hasClass('t794__tooltip-menu_show')){return}
clearTimeout(timer);if($(this).hasClass('t794__tooltip-menu')&&submenu.hasClass('t794__tooltip-menu_show')){return}
var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)});hookLinks.add(submenu).on('mouseout',function(){timer=setTimeout(function(){t794_hideSubmenu(submenu)},300)});hookLinks.on('click',function(e){e.preventDefault()})}
function t794_showSubmenu(curAnchor,submenu,vIndent){var isFirefox=navigator.userAgent.search("Firefox")!==-1;var submenuHeight=submenu.outerHeight();var submenuWidth=submenu.outerWidth();var anchorHeight=curAnchor.height();var anchorWidth=curAnchor.width();if(curAnchor.hasClass('t-btn')){anchorWidth=curAnchor.outerWidth()}
var winHeight=$(window).height();var winWidth=$(window).width();var scrollTop=$(window).scrollTop();var anchorLeft=curAnchor.offset().left;var anchorTop=curAnchor.offset().top;submenu.attr('data-pos-fixed','no');var parentMenu=curAnchor.closest('[data-menu="yes"]');var parentZeroMenu=curAnchor.closest('.t396__artboard');if(parentMenu.length&&parentMenu.css('position')==='fixed'){submenu.attr('data-pos-fixed','yes')}
var menuFixed=submenu.attr('data-pos-fixed');var submenuContent=submenu.find('.t794__content');if(typeof vIndent!='undefined'&&vIndent!=''){vIndent=vIndent.replace('px','')*1;vIndent=vIndent+10}
var posy;if(menuFixed=='yes'){posy=(anchorTop-scrollTop)+anchorHeight+vIndent;submenu.css('position','fixed');submenu.removeClass('t794__tooltip-menu_top').addClass('t794__tooltip-menu_bottom');submenuContent.css('max-height','calc(100vh - '+posy+'px)')}else{posy=anchorTop+anchorHeight+vIndent;submenu.css('position','absolute');var topSpace=anchorTop-scrollTop,bottomSpace=winHeight-topSpace;if(posy+submenuHeight>scrollTop+winHeight&&topSpace>bottomSpace){posy=posy-submenuHeight-anchorHeight-vIndent*2;submenu.removeClass('t794__tooltip-menu_bottom').addClass('t794__tooltip-menu_top')}else{submenu.removeClass('t794__tooltip-menu_top').addClass('t794__tooltip-menu_bottom')}}
var posx=anchorLeft;if(parentZeroMenu.hasClass('t396__artboard_scale')&&window.tn_scale_factor){posx=isFirefox?posx:posx*window.tn_scale_factor;anchorWidth=anchorWidth*window.tn_scale_factor}
if(posx+submenuWidth/2<winWidth){posx=posx+(anchorWidth-submenuWidth)/2;if(posx<0){posx=10}}else{posx=winWidth-submenuWidth-10}
submenu.css({'display':'block','left':posx,'top':posy});submenu[0].offsetHeight;submenu.addClass('t794__tooltip-menu_show');curAnchor.addClass('t794__tm-link_active')}
function t794_hideSubmenu(submenu){submenu.css({'display':'','left':'','top':''});submenu.removeClass('t794__tooltip-menu_show');$('.t794__tm-link_active').removeClass('t794__tm-link_active')}
function t794_addArrow(recid,hookLinks){var arrow=$('#rec'+recid+' .t794').attr('data-add-arrow');if(typeof arrow==='undefined'||arrow===''){return}
hookLinks.each(function(i,el){$(el).append('<div class="t794__arrow"></div>')})}
function t794_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=='/'){pathname=pathname.slice(1)}
if(pathname==''){pathname='/'}
$('.t794__list_item a[href="'+url+'"]').addClass('t-active');$('.t794__list_item a[href="'+url+'/"]').addClass('t-active');$('.t794__list_item a[href="'+pathname+'"]').addClass('t-active');$('.t794__list_item a[href="/'+pathname+'"]').addClass('t-active');$('.t794__list_item a[href="'+pathname+'/"]').addClass('t-active');$('.t794__list_item a[href="/'+pathname+'/"]').addClass('t-active');if(hash){$('.t794__list_item a[href="'+hash+'"]').addClass('t-active')}}
function t862_init(recid){var rec=$('#rec'+recid);var quizWrapper=rec.find('.t862__quiz-wrapper');var form=rec.find('.t862 .t-form');var quizQuestion=rec.find('.t862 .t-input-group');var prevBtn=rec.find('.t862__btn_prev');var nextBtn=rec.find('.t862__btn_next');var resultBtn=rec.find('.t862__btn_result');var errorBoxMiddle=rec.find('.t-form__errorbox-middle .t-form__errorbox-wrapper');var captureFormHTML='<div class="t862__capture-form"></div>';rec.find('.t862 .t-form__errorbox-middle').before(captureFormHTML);var quizQuestionNumber=0;form.removeClass('js-form-proccess');$(quizQuestion[quizQuestionNumber]).show();$(quizQuestion[quizQuestionNumber]).addClass('t-input-group-step_active');rec.attr('data-animationappear','off');rec.css('opacity','1');t862_workWithAnswerCode(rec);quizQuestion.each(function(i){$(quizQuestion[i]).attr('data-question-number',i)});t862_wrapCaptureForm(rec);var captureForm=rec.find('.t862__capture-form');var resultText=rec.find('.t862__result-title').text();t862_showCounter(rec,quizQuestionNumber);t862_disabledPrevBtn(rec,quizQuestionNumber);t862_checkLength(rec);t862_openToHook(rec,form,quizQuestion,captureForm);prevBtn.click(function(e){if(quizQuestionNumber>0){quizQuestionNumber--}
t862_setProgress(rec,-1);t862_lazyLoad();t862_awayFromResultScreen(rec);t862_showCounter(rec,quizQuestionNumber);t862_hideError(rec,quizQuestionNumber);t862_disabledPrevBtn(rec,quizQuestionNumber);t862_switchQuestion(rec,quizQuestionNumber);t862_resizePopup(rec);e.preventDefault()});nextBtn.click(function(e){var showErrors=t862_showError(rec,quizWrapper,quizQuestionNumber);if(showErrors){errorBoxMiddle.hide()}
if(!showErrors){quizQuestionNumber++;prevBtn.attr('disabled',!1);t862_setProgress(rec,1);t862_showCounter(rec,quizQuestionNumber);t862_switchQuestion(rec,quizQuestionNumber);t862_resizePopup(rec)}
t862_lazyLoad();e.preventDefault()});quizQuestion.keypress(function(e){var activeStep=form.find('.t-input-group-step_active');if(event.keyCode===13&&!form.hasClass('js-form-proccess')&&!activeStep.hasClass('t-input-group_ta')){var showErrors=t862_showError(rec,quizWrapper,quizQuestionNumber);var questionArr=t862_createQuestionArr(rec);if(showErrors){errorBoxMiddle.hide()}
prevBtn.attr('disabled',!1);if(!showErrors){quizQuestionNumber++;t862_setProgress(rec,1);t862_showCounter(rec,quizQuestionNumber);if(quizQuestionNumber<questionArr.length){t862_switchQuestion(rec,quizQuestionNumber)}else{t862_switchResultScreen(rec);form.addClass('js-form-proccess')}
t862_disabledPrevBtn(rec,quizQuestionNumber)}
t862_lazyLoad();e.preventDefault()}});resultBtn.click(function(e){var showErrors=t862_showError(rec,quizWrapper,quizQuestionNumber);if(showErrors){errorBoxMiddle.hide()}
if(!showErrors){quizQuestionNumber++;t862_setProgress(rec,1);form.addClass('js-form-proccess');t862_disabledPrevBtn(rec,quizQuestionNumber);if(captureForm.html()===''&&resultText===''){t862_showCounter(rec,quizQuestionNumber);t862_switchQuestion(rec,quizQuestionNumber)}else{t862_switchResultScreen(rec)}}
e.preventDefault()})}
function t862_workWithAnswerCode(rec){rec.find('.t-input-group_ri').find('input').each(function(){var $this=$(this);if($this.val().indexOf('value::')!=-1){t862_setAnswerCode($this);var label=$this.parent().find('.t-img-select__text');label.text(label.text().split('value::')[0].trim())}});rec.find('.t-input-group_rd').find('input').each(function(){var $this=$(this);if($this.val().indexOf('value::')!=-1){t862_setAnswerCode($this);var label=$this.parent();label.html(function(){var html=$(this).html().split('value::')[0].trim();return html})}});rec.find('.t-input-group_sb').find('option').each(function(){var $this=$(this);if($this.val().indexOf('value::')!=-1){t862_setAnswerCode($this);$this.text($this.text().split('value::')[0].trim())}})}
function t862_setAnswerCode($this){var parameter=$this.val().split('value::')[1].trim();$this.val(parameter)}
function t862_openToHook(rec,form,quizQuestion,captureForm){var popup=rec.find('.t-popup');var hook=popup.attr('data-tooltip-hook');var analitics=popup.attr('data-track-popup');if(hook!==''){$('.r').on('click','a[href="'+hook+'"]',function(e){t862_showPopup(rec,form,quizQuestion,captureForm);setTimeout(function(){t862_resizePopup(rec)},50);e.preventDefault();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t862_showError(rec,quizWrapper,quizQuestionNumber){if(quizWrapper.hasClass('t862__quiz-published')){var errors=t862_setError(rec,quizQuestionNumber);return errors}}
function t862_lazyLoad(){if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}}
function t862_setHeight(rec,form,quizQuestion,captureForm){var questions=[];var questionsHeight=[];var descrHeight=rec.find('.t862__quiz-description').outerHeight();var titleHeight=rec.find('.t862__result-title').outerHeight();quizQuestion.each(function(){var $this=$(this);if(!$this.hasClass('t862__t-input-group_capture')){questions.push($this)}});questions.forEach(function(item){questionsHeight.push(item.outerHeight())});var maxHeightQuestion=Math.max.apply(null,questionsHeight);var captureFormHeight=captureForm.outerHeight();var height=maxHeightQuestion>captureFormHeight?maxHeightQuestion:captureFormHeight;questions.forEach(function(item){item.css('min-height',height)});captureForm.css('min-height',height);rec.find('.t862__quiz-form-wrapper').css('min-height',height);var headerHeight=titleHeight>descrHeight?titleHeight:descrHeight;var quizWrapperHeight=rec.find('.t862__quiz-form-wrapper').outerHeight();var btnHeight=rec.find('.t862__btn-wrapper').outerHeight();rec.find('.t862__wrapper').css('min-height',headerHeight+quizWrapperHeight+btnHeight)}
function t862_setMobileHeight(){t862_calcVH();window.addEventListener('resize',function(){t862_calcVH()})}
function t862_calcVH(){var vh=window.innerHeight*0.01;document.documentElement.style.setProperty('--vh',vh+'px')}
function t862_checkLength(rec){var nextBtn=rec.find('.t862__btn_next');var resultBtn=rec.find('.t862__btn_result');var questionArr=t862_createQuestionArr(rec);var submitBtnWrapper=rec.find('.t862 .t-form__submit');var captureForm=rec.find('.t862__capture-form');var resultText=rec.find('.t862__result-title').text();if(captureForm.html()===''&&resultText===''&&questionArr.length<2){nextBtn.hide();resultBtn.hide();submitBtnWrapper.show()}else if(questionArr.length<2){nextBtn.hide();resultBtn.show()}}
function t862_showCounter(rec,quizQuestionNumber){var counter=rec.find('.t862__quiz-description-counter');var questionArr=t862_createQuestionArr(rec);counter.html(quizQuestionNumber+1+'/'+questionArr.length)}
function t862_setError(rec,quizQuestionNumber){var questionArr=t862_createQuestionArr(rec);var currentQuestion=$(questionArr[quizQuestionNumber]);var showErrors;if(typeof window.tildaForm!=='object')return showErrors;var arErrors=window.tildaForm.validate(currentQuestion);currentQuestion.addClass('js-error-control-box');var errorsTypeObj=arErrors[0];if(errorsTypeObj!=undefined){var errorType=errorsTypeObj.type[0];var errorTextCustom=rec.find('.t862 .t-form').find('.t-form__errorbox-middle').find('.js-rule-error-'+errorType).text();var sError='';if(errorTextCustom!=''){sError=errorTextCustom}else{t_onFuncLoad('t_form_dict',function(){sError=t_form_dict(errorType)})}
showErrors=errorType=='emptyfill'?!1:window.tildaForm.showErrors(currentQuestion,arErrors);currentQuestion.find('.t-input-error').html(sError)}
return showErrors}
function t862_hideError(rec,quizQuestionNumber){var questionArr=t862_createQuestionArr(rec);var currentQuestion=$(questionArr[quizQuestionNumber]);currentQuestion.removeClass('js-error-control-box');currentQuestion.find('.t-input-error').html('')}
function t862_setProgress(rec,index){var progress=rec.find('.t862__progress');var progressbarWidth=rec.find('.t862__progressbar').width();var questionCount=t862_createQuestionArr(rec).length;var captureForm=rec.find('.t862__capture-form');var resultText=rec.find('.t862__result-title').text();if(captureForm.html()===''&&resultText===''&&questionCount>0){questionCount--}
var progressWidth=progress.attr('data-progress-bar');if(progressWidth===undefined){progressWidth=0;progress.attr('data-progress-bar','0')}
var progressStep=progressbarWidth/questionCount;var percentProgress=(parseFloat(progressWidth)+(index*progressStep))/progressbarWidth*100;if(isNaN(percentProgress)||percentProgress===-Infinity){percentProgress=0;progress.attr('data-progress-bar',percentProgress)}else if(percentProgress===Infinity){percentProgress=progressbarWidth;progress.attr('data-progress-bar',percentProgress)}else{progress.attr('data-progress-bar',progressbarWidth/100*percentProgress)}
if(percentProgress>100){percentProgress=100}else if(percentProgress<0){percentProgress=0}
var percentProgressWidth=percentProgress+'%';progress.css('width',percentProgressWidth)}
function t862_wrapCaptureForm(rec){var captureForm=rec.find('.t862__capture-form');var quizQuestion=rec.find('.t862 .t-input-group');var quizFormWrapper=rec.find('.t862__quiz-form-wrapper');quizQuestion.each(function(i){var currentQuizQuestion=$(quizQuestion[i]);var emailInputExist=$(currentQuizQuestion).hasClass('t-input-group_em');var nameInputExist=$(currentQuizQuestion).hasClass('t-input-group_nm');var phoneInputExist=$(currentQuizQuestion).hasClass('t-input-group_ph');var checkboxInputExist=$(currentQuizQuestion).hasClass('t-input-group_cb');var quizQuestionNumber=currentQuizQuestion.attr('data-question-number');var maxCountOfCaptureFields=4;if(quizQuestionNumber>=quizQuestion.length-maxCountOfCaptureFields){var isCaptureGroup=!0;if(quizFormWrapper.hasClass('t862__quiz-form-wrapper_newcapturecondition')){var inputsGroup=currentQuizQuestion.nextAll('.t-input-group');inputsGroup.each(function(){isCaptureGroup=$(this).hasClass('t-input-group_cb')||$(this).hasClass('t-input-group_em')||$(this).hasClass('t-input-group_nm')||$(this).hasClass('t-input-group_ph')})}
if(isCaptureGroup){if(emailInputExist||nameInputExist||phoneInputExist||checkboxInputExist){currentQuizQuestion.addClass('t862__t-input-group_capture');captureForm.append(currentQuizQuestion)}}}})}
function t862_createQuestionArr(rec){var quizQuestion=rec.find('.t862 .t-input-group');var questionArr=[];quizQuestion.each(function(i){var question=$(quizQuestion[i]);if(!question.hasClass('t862__t-input-group_capture')){questionArr.push(quizQuestion[i])}});return questionArr}
function t862_disabledPrevBtn(rec,quizQuestionNumber){var prevBtn=rec.find('.t862__btn_prev');quizQuestionNumber==0?prevBtn.attr('disabled',!0):prevBtn.attr('disabled',!1)}
function t862_switchQuestion(rec,quizQuestionNumber){var nextBtn=rec.find('.t862__btn_next');var resultBtn=rec.find('.t862__btn_result');var questionArr=t862_createQuestionArr(rec);var submitBtnWrapper=rec.find('.t862 .t-form__submit');var captureForm=rec.find('.t862__capture-form');var resultText=rec.find('.t862__result-title').text();$(questionArr).hide();$(questionArr).removeClass('t-input-group-step_active');$(questionArr[quizQuestionNumber]).show();$(questionArr[quizQuestionNumber]).addClass('t-input-group-step_active');var $range=$(questionArr[quizQuestionNumber]).find('.t-range');$range.trigger('displayChanged');var range=$range.get(0);if(range){var triggerChangeEvent;if(/msie|trident/.test(navigator.userAgent)){triggerChangeEvent=document.createEvent('Event');triggerChangeEvent.initEvent('displayChanged',!0,!1)}else{triggerChangeEvent=new Event('displayChanged')}
range.dispatchEvent(triggerChangeEvent)}
if(captureForm.html()===''&&resultText===''&&quizQuestionNumber===questionArr.length-2){nextBtn.hide();resultBtn.show();submitBtnWrapper.hide()}else if(captureForm.html()===''&&resultText===''&&quizQuestionNumber===questionArr.length-1){nextBtn.hide();resultBtn.hide();submitBtnWrapper.show()}else if(quizQuestionNumber===questionArr.length-1){nextBtn.hide();resultBtn.show();submitBtnWrapper.hide()}else{nextBtn.show();resultBtn.hide();submitBtnWrapper.hide()}}
function t862_switchResultScreen(rec){var resultBtn=rec.find('.t862__btn_result');var submitBtnWrapper=rec.find('.t862 .t-form__submit');var captureForm=rec.find('.t862__capture-form');var resultTitle=rec.find('.t862__result-title');if(captureForm.html()!==''||resultTitle.text()!==''){var quizDescription=rec.find('.t862__quiz-description');var questionArr=t862_createQuestionArr(rec);$(questionArr).hide();$(captureForm).show();quizDescription.hide();resultTitle.show()}
resultBtn.hide();submitBtnWrapper.show()}
function t862_awayFromResultScreen(rec){var captureForm=rec.find('.t862__capture-form');var quizDescription=rec.find('.t862__quiz-description');var resultTitle=rec.find('.t862__result-title');var submitBtnWrapper=rec.find('.t862 .t-form__submit');submitBtnWrapper.hide();$(captureForm).hide();quizDescription.show();resultTitle.hide()}
function t862_onSuccess(form){var inputsWrapper=form.find('.t-form__inputsbox');var inputsHeight=inputsWrapper.height();var inputsOffset=inputsWrapper.offset().top;var inputsBottom=inputsHeight+inputsOffset;var targetOffset=form.find('.t-form__successbox').offset().top;var prevBtn=form.parents('.t862').find('.t862__btn_prev');var target;if($(window).width()>960){target=targetOffset-200}else{target=targetOffset-100}
if(targetOffset>$(window).scrollTop()||$(document).height()-inputsBottom<$(window).height()-100){inputsWrapper.addClass('t862__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0,},50)}},300)}else{$('html, body').animate({scrollTop:target,},400);setTimeout(function(){inputsWrapper.addClass('t862__inputsbox_hidden')},400)}
var successurl=form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}
prevBtn.hide()}
function t862_lockScroll(){var body=$('body');if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css('top','-'+bodyScrollTop+'px');body.attr('data-popup-scrolltop',bodyScrollTop)}}
function t862_unlockScroll(){var body=$('body');if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$('body').attr('data-popup-scrolltop');body.removeClass('t-body_scroll-locked');body.css('top','');body.removeAttr('data-popup-scrolltop');window.scrollTo(0,bodyScrollTop)}}
function t862_showPopup(rec,form,quizQuestion,captureForm){var popup=rec.find('.t-popup');var quiz=rec.find('.t862__quiz');popup.css('display','block');var $range=rec.find('.t-range');$range.trigger('popupOpened');var range=$range.get(0);if(range){var triggerChangeEvent;if(/msie|trident/.test(navigator.userAgent)){triggerChangeEvent=document.createEvent('Event');triggerChangeEvent.initEvent('popupOpened',!0,!1)}else{triggerChangeEvent=new Event('popupOpened')}
range.dispatchEvent(triggerChangeEvent)}
if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show');if($(window).width()>640&&quiz.hasClass('t862__quiz_fixedheight')){t862_setHeight(rec,form,quizQuestion,captureForm)}
if($(window).width()<=640){t862_setMobileHeight()}
t862__showJivo(popup,'1','1')},50);$('body').addClass('t-body_popupshowed t862__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t862_lockScroll()},500)}
rec.find('.t-popup').click(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t862_closePopup(rec)}});rec.find('.t-popup__close').click(function(){t862_closePopup(rec)});rec.find('a[href*="#"]').click(function(){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t862_closePopup(rec);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t862_closePopup(rec)}})}
function t862_closePopup(rec){$('body').removeClass('t-body_popupshowed t862__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t862_unlockScroll()}
rec.find('.t-popup').removeClass('t-popup_show');t862__showJivo($('.t-popup'),'2147483647','2147483648');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t862_resizePopup(rec){var div=rec.find('.t-popup__container').height();var win=$(window).height()-120;var popup=rec.find('.t-popup__container');if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t862__showJivo(popup,indexMobile,indexDesktop){if($('._show_1e.wrap_mW.__jivoMobileButton').length!=0){$('._show_1e.wrap_mW.__jivoMobileButton').css('z-index',indexMobile)}
if($('.label_39#jvlabelWrap').length!=0){$('.label_39#jvlabelWrap').css('z-index',indexDesktop)}}
function t862_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle,})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href,})}}}
function t937_init(recid,styles){var rec=document.getElementById('rec'+recid);var playlist=rec.querySelector('.t937__playlist-wrap');var videoColumn=rec.querySelector('.t937__col_video');var videoData=t937_parseData(recid);var params=t937_getUrlParametrs(recid);var activeVideoId=params.activeVideoId;t937_setSizes(recid,styles);t937_renderVideoCount(videoData,recid,styles);t937_renderPlaylist(videoData,activeVideoId,recid,styles);t937_renderVideoFrame(videoData,activeVideoId,recid,styles);if(videoColumn)videoColumn.style.height='';if(playlist)playlist.style.visibility='visible';t937_addEvents(recid,styles)}
function t937_getUrlParametrs(recid){var activeRecId;var activeVideoId;var hash=window.location.hash;if(hash&&hash.indexOf('#tlection=')===-1){activeRecId=recid;activeVideoId=1}else{var params=hash.replace('#tlection=','').split('_');activeRecId=params[0];activeVideoId=+recid===+activeRecId?params[1]:1}
return{activeRecId:activeRecId,activeVideoId:activeVideoId,}}
function t937_parseData(recid){var rec=document.getElementById('rec'+recid);var recData=rec?rec.querySelector('.t937__data'):null;var data=recData?recData.innerHTML:'';var videos=[];if(data){data=data.replace(/&amp;/gi,'&');var segments=data.split('\n');for(var i=0;i<segments.length;i++){var segment=segments[i];var parts=segment.split(';');var video=t937_getVideoData(parts);if(video.url||video.section){videos.push(video)}}}
return videos}
function t937_getVideoData(data){var first=data[0].trim();if(first.indexOf('[')===0&&first.indexOf(']')===first.length-1){return{section:first.slice(1,-1),}}
var url=data[0]&&data[0].length?data[0].trim():null;var title=data[1]?data[1].trim():null;var time=data[2]?data[2].trim():null;var description=data[3]?data[3].trim():null;var type=null;if(/youtube.com|youtu.be/gi.test(url)){type='youtube'}
if(/vimeo.com/gi.test(url)){type='vimeo'}
return{url:url,title:title,time:time,description:description,type:type,}}
function t937_renderPlaylist(videoData,activeVideoId,recid,styles){var rec=document.getElementById('rec'+recid);var container=rec.querySelector('.t937__playlist');if(container)container.dataVideoContent=videoData;if(container)container.dataPlaylistStyles=styles;var videoCount=1;t937_setSizes(recid,styles);if(container)container.innerHTML='';var mainColor=styles.mainColor.length?'color: '+styles.mainColor+';':'';var secondaryColor=styles.secondaryColor.length?'color: '+styles.secondaryColor+';':'';var border=styles.borderColor.length?'border-bottom: 1px solid '+styles.borderColor+';':'';t937_renderFade(recid,styles.bgColor);for(var i=0;i<videoData.length;i++){var data=videoData[i];var id=i+1;var isActive=Number(id)===Number(activeVideoId);var item;if(Object.prototype.hasOwnProperty.call(data,'section')){item=document.createElement('div');item.classList.add('t937__playlist-item','t937__playlist-item_section');item.setAttribute('style',border);var itemChild=document.createElement('div');itemChild.classList.add('t937__playlist-section','t-name','t-name_xs');itemChild.setAttribute('style',mainColor);itemChild.textContent=data.section;item.insertAdjacentElement('beforeend',itemChild)}else{var title=data.title&&data.title.length?data.title:t937_translate('videoTitle');var time=data.time?data.time:'';var linkBgColor=isActive&&styles.linkBgColor.length?'background-color: '+styles.linkBgColor+';':'';item=document.createElement('div');item.classList.add('t937__playlist-item');item.setAttribute('data-video-id',id.toString());item.setAttribute('style',border);item.setAttribute('onclick','window.t937_onVideoClick('+id+', '+recid+')');var playlistLink=document.createElement('div');if(isActive){playlistLink.classList.add('t937__playlist-link','t-text','t-text_xs','t937__playlist-link_active')}else{playlistLink.classList.add('t937__playlist-link','t-text','t-text_xs')}
playlistLink.setAttribute('style',linkBgColor);var playlistNumber=document.createElement('div');playlistNumber.classList.add('t937__playlist-number');playlistNumber.setAttribute('style',secondaryColor);playlistNumber.textContent=videoCount.toString();var playlistTitle=document.createElement('div');playlistTitle.classList.add('t937__playlist-title');playlistTitle.setAttribute('style',mainColor);playlistTitle.textContent=title;var playlistTime=document.createElement('div');playlistTime.classList.add('t937__playlist-time');playlistTime.setAttribute('style',secondaryColor);playlistTime.textContent=time;playlistLink.insertAdjacentElement('beforeend',playlistNumber);playlistLink.insertAdjacentElement('beforeend',playlistTitle);playlistLink.insertAdjacentElement('beforeend',playlistTime);item.insertAdjacentElement('beforeend',playlistLink);item.addEventListener('mousemove',function(e){var currentItem=e.target.closest('.t937__playlist-item');currentItem.style.backgroundColor=styles.linkBgColor.length?styles.linkBgColor:'#F0F0F0'});item.addEventListener('mouseout',function(e){var currentItem=e.target.closest('.t937__playlist-item');currentItem.style.backgroundColor=''});videoCount++}
if(container)container.insertAdjacentElement('beforeend',item)}}
function t937_renderVideoFrame(data,activeVideoId,recid){var rec=document.getElementById('rec'+recid);var frame;var video;var container=rec?rec.querySelector('.t937__video'):null;var height=container?container.offsetWidth*0.5625:0;if(container)container.classList.remove('t937__video_empty');var id;for(var i=activeVideoId-1;i<data.length;i++){if(data[i].url){video=data[i];t937_renderDescription(video,recid);break}}
if(!data.length||!video||!video.type){if(container)container.classList.add('t937__video_empty');frame=document.createElement('div');frame.classList.add('t937__system-message');frame.textContent=!data.length?t937_translate('noData'):t937_translate('wrongFormat')}else if(video.type==='youtube'){var regex=/youtu(?:.*\/v\/|.*v\=|\.be\/)([A-Za-z0-9_\-]{11})/;id=video.url.match(regex);if(id!==null){id=id[1]}
frame=document.createElement('iframe');frame.classList.add('t937__video-frame','t937__video-frame_youtube');frame.width='100%';frame.height=height.toString();frame.src='https://www.youtube.com/embed/'+id+'?rel=0&fmt=18&html5=1&enablejsapi=1';frame.frameBorder='0';frame.setAttribute('allow','accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture');frame.setAttribute('allowfullscreen','')}else if(video.type==='vimeo'){var idMatch=/vimeo[^/]*\/(\d+)\/?(\w*)\/?/i.exec(video.url);id=idMatch?idMatch[1]:null;var hash=idMatch?'?h='+idMatch[2]:null;var timecodeMatch=/#t=(\d*h)?(\d*m)?\d*s$/i.exec(video.url);var timecode=timecodeMatch?'/'+timecodeMatch[0]:'';if(!id){if(container)container.classList.add('t937__video_empty');frame=document.createElement('div');frame.classList.add('t937__system-message');frame.textContent=t937_translate('wrongFormat')}else{frame=document.createElement('iframe');frame.classList.add('t937__video-frame','t937__video-frame_vimeo');frame.title='vimeo-player';frame.width='100%';frame.height=height.toString();frame.src='https://player.vimeo.com/video/'+id+hash+timecode;frame.frameBorder='0';frame.setAttribute('allowfullscreen','')}}
if(container){container.innerHTML='';container.insertAdjacentElement('beforeend',frame)}}
function t937_renderDescription(videoData,recid){var rec=document.getElementById('rec'+recid);var wrapper=rec?rec.querySelector('.t937__col_description'):null;var titleContainer=wrapper?wrapper.querySelector('.t937__video-title'):null;var descriptionContainer=wrapper?wrapper.querySelector('.t937__video-description'):null;if(wrapper)wrapper.classList.add('t937__col_hidden');if(titleContainer)titleContainer.innerHTML='';if(descriptionContainer)descriptionContainer.innerHTML='';if(!videoData.description)return;if(wrapper)wrapper.classList.remove('t937__col_hidden');var title=videoData.title&&videoData.title.length?videoData.title:t937_translate('videoTitle');var descriptionContent=t937_parseDescription(videoData.description);titleContainer.textContent=title;Array.prototype.forEach.call(descriptionContent,function(content){if(descriptionContainer)descriptionContainer.insertAdjacentElement('beforeend',content)})}
function t937_renderVideoCount(data,recid,styles){var rec=document.getElementById('rec'+recid);var subheading=rec?rec.querySelector('.t937__subheading-title'):null;var icon=rec?rec.querySelector('.t937__subheading-icon'):null;var size=0;var color=styles.secondaryColor.length?styles.secondaryColor.replace('#','%23'):'%23111111';if(icon)icon.style.backgroundImage='url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 16 16\' width=\'16\' height=\'16\'%3E%3Ctitle%3Evideo playlist%3C/title%3E%3Cg class=\'nc-icon-wrapper\' stroke-width=\'1\' fill='+'\''+color+'\''+' stroke='+'\''+color+'\''+'%3E%3Crect x=\'0.5\' y=\'2.5\' width=\'15\' height=\'12\' rx=\'1\' fill=\'none\' stroke='+'\''+color+'\''+' stroke-linecap=\'round\' stroke-linejoin=\'round\'/%3E%3Cpolygon points=\'6.5 5.5 11.5 8.5 6.5 11.5 6.5 5.5\' fill=\'none\' stroke-linecap=\'round\' stroke-linejoin=\'round\' data-color=\'color-2\'/%3E%3Cline x1=\'3.5\' y1=\'0.5\' x2=\'12.5\' y2=\'0.5\' fill=\'none\' stroke='+'\''+color+'\''+' stroke-linecap=\'round\' stroke-linejoin=\'round\'/%3E%3C/g%3E%3C/svg%3E\"';for(var item in data){if(!data[item].section){size++}}
var videoPart=t937_translate('videoPart');if(subheading)subheading.textContent=size+' '+videoPart}
function t937_renderFade(recid,color){color=color.length?color:'#ffffff';var rec=document.getElementById('rec'+recid);var playlistFade=rec?rec.querySelector('.t937__playlist-fade'):null;var colorFrom=t937_hex2rgb(color,0);var colorTo=t937_hex2rgb(color,1);if(playlistFade)playlistFade.style.backgroundImage='linear-gradient('+colorFrom+' 0%, '+colorTo+' 90%)'}
function t937_parseDescription(string){var result=[];var parts=string.split('<br>');var res;parts.forEach(function(part){if(!part.length){res=document.createElement('br');result.push(res)}else{res=document.createElement('p');res.classList.add('t937__paragraph');res.innerHTML=part;result.push(res)}});return result}
function t937_setSizes(recid,styles){var rec=document.getElementById('rec'+recid);var playlistWrapper=rec?rec.querySelector('.t937__playlist-wrap'):null;var iframe=rec?rec.querySelector('.t937__video-frame'):null;var playlistCol=rec?rec.querySelector('.t937__col_playlist'):null;var description=rec?rec.querySelector('.t937__description'):null;var videoCol=rec?rec.querySelector('.t937__video'):null;var videoColWidth=videoCol?videoCol.offsetWidth:0;var height=videoColWidth*0.5625;if(iframe)iframe.setAttribute('height',height.toString());if(window.innerWidth>=960){if(description)description.style.width=videoColWidth+'px';if(playlistWrapper)playlistWrapper.style.height=height+'px';if(playlistWrapper)playlistWrapper.style.maxHeight='';if(styles.playlistWidth.length){if(playlistCol)playlistCol.style.width=parseInt(styles.playlistWidth,10)+'px'}}else{if(playlistWrapper)playlistWrapper.style.maxHeight=height+'px';if(playlistWrapper)playlistWrapper.style.height='';if(playlistCol)playlistCol.style.width='';if(description)description.style.width=''}}
function t937_translate(keyword){var dict=[];dict.videoTitle={RU:'Без названия',EN:'Untitled video',FR:'Vidéo sans titre',DE:'Video ohne Titel',ES:'Video sin título',PT:'Bez tytułu wideo',UK:'Відео без назви',JA:'無題の動画',ZH:'无标题的视频',PL:'Bez tytułu',};dict.videoPart={RU:'видео',EN:'videos',FR:'vidéos',DE:'videos',ES:'videos',PT:'filmy',UK:'відео',JA:'ビデオ',ZH:'影片',PL:'video',};dict.noData={RU:'Пожалуйста, добавьте хотя бы одно видео в плейлист',EN:'Please add at least one video to the playlist',UK:'Будь ласка, додайте хоча б одне відео в плейлист',PL:'Proszę dodać jeden filmik do listy',};dict.wrongFormat={RU:'Пожалуйста, проверьте корректность заполненных данных',EN:'Please check that the data is filled in correctly',UK:'Будь ласка, перевірте коректність заповнених даних',PL:'Sprawdź poprawność danych',};var lang=window.browserLang;if(dict[keyword]!==undefined){if(dict[keyword][lang]!==undefined&&dict[keyword][lang]!==''){return dict[keyword][lang]}else{return dict[keyword].EN}}
return 'Text not found #'+keyword}
function t937_hex2rgb(hex,opacity){var h=hex.replace('#','');h=h.match(new RegExp('(.{'+h.length/3+'})','g'));for(var i=0;i<h.length;i++){h[i]=parseInt(h[i].length===1?h[i]+h[i]:h[i],16)}
if(typeof opacity!='undefined'){h.push(opacity)}
return 'rgba('+h.join(',')+')'}
function t937_addEvents(recid,styles){window.addEventListener('resize',t_throttle(function(){t937_setSizes(recid,styles)}));if(typeof jQuery!=='undefined'){$('.t937').bind('displayChanged',function(){t937_setSizes(recid,styles)})}else{var currentBlocks=document.querySelectorAll('.t937');Array.prototype.forEach.call(currentBlocks,function(block){block.addEventListener('displayChanged',function(){t937_setSizes(recid,styles)})})}
var rec=document.getElementById('rec'+recid);var playlistWrap=rec?rec.querySelector('.t937__playlist-wrap'):null;var playlistFade=rec?rec.querySelector('.t937__playlist-fade'):null;if(playlistWrap){playlistWrap.addEventListener('scroll',function(){var currentHeight=playlistWrap.offsetHeight;var scrollTop=playlistWrap.scrollTop;var scrollHeight=playlistWrap.scrollHeight;var marginBottom=30;if(currentHeight+scrollTop>=scrollHeight-marginBottom){if(playlistFade)playlistFade.style.backgroundImage=''}else{t937_renderFade(recid,styles.bgColor)}})}}
function t937_onVideoClick(id,recid){var rec=document.getElementById('rec'+recid);var container=rec?rec.querySelector('.t937__playlist'):null;var videoData=container?container.dataVideoContent:null;var styles=container?container.dataPlaylistStyles:null;window.location.hash='tlection='+recid+'_'+id;t937_renderPlaylist(videoData,id,recid,styles);t937_renderVideoFrame(videoData,id,recid,styles);t937_playVideo(recid)}
function t937_playVideo(recid){var rec=document.getElementById('rec'+recid);var videoFrame=rec?rec.querySelector('.t937__video-frame'):null;if(videoFrame&&videoFrame.classList.contains('t937__video-frame_youtube')){videoFrame.addEventListener('load',function(){var command='playVideo';videoFrame.contentWindow.postMessage('{"event":"command","func":"'+command+'","args":""}','*')})}}